FORMAT: 1A
HOST: https://nonexistent.ispringsolutions.com

# Test Constructor API
This API Blueprint contain Test constructor demo app API.

NOTE: This document is a **work in progress**.

# Tests
This section groups Test Constructor tests resources.

## Test [/tc/v1/tests/{id}]
A Test is central object utilized by the Test constructor API. Tests are closely tied to the follow graph...

+ Parameters
    + id: `0221FD76-B549-45A1-81E9-A807E09C926B` - The id of the Test.

+ Model (application/json)

    ```js
    {
        "data": {
            "id": "0221FD76-B549-45A1-81E9-A807E09C926B",
            "name": "Test name",
            "content": "Test content",
        }
    }
    ```

### Retrieve a Test [GET]
Returns a specific Test.

+ Response 200 (application/json)

        [Test][]

### Delete a Test [DELETE]
Delete a Test.

+ Response 200

## Tests Collection [/tc/v1/tests]
A Collection of tests.

+ Model (application/json)

    ```js
    {
        "tests": [
            {
                "id": "0221FD76-B549-45A1-81E9-A807E09C926B",
                ...
            },
            {
                "id": "0221FD76-B549-45A1-81E9-A807E09C926C",
                ...
            },
            {
                "id": "0221FD76-B549-45A1-81E9-A807E09C926D",
                ...
            },
        ],
    }
    ```

### Create a Test [POST]
Create a new Test object.

+ Request (application/json)

    + Attributes

        + name: Test name (required)

+ Response 200

    + Attributes

        + id: Test id

### Retrieve all Tests [GET]
Retrieves all tests.

+ Response 200

    [Tests Collection][]